// Generated by `rindle schema gen` from the daemon's introspected schema (GET /schema).
// Do not edit by hand — re-run the generator after each migration.
//
// Column kinds come from your declared SQL types: TEXT maps to string(), INTEGER/REAL to
// number(), and a column declared BOOLEAN/BOOL or JSON to boolean()/json(). The only thing the
// SQL can't carry is a refinement *within* a kind — the element type of json<T>(), or a
// string/number literal union — declare those ONCE in a hand-written module with
// refineTable(...) + refineSchema(...); they survive every regen of this file.

import { createSchema, number, string, table } from "@rindle/client";

export const todo = table("todo")
  .columns({
    id: string(),
    listId: string(),
    title: string(),
    completed: number(),
    temperature: number(),
    createdAt: number(),
    updatedAt: number(),
    color: number(),
  })
  .primaryKey("id");

export const todo_list = table("todo_list")
  .columns({
    id: string(),
    name: string(),
    createdAt: number(),
  })
  .primaryKey("id");

export const schema = createSchema({ tables: [todo, todo_list] });
