/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BoardRouteImport } from './routes/board'
import { Route as MineRouteImport } from './routes/mine'
import { Route as ApiRindleMutateRouteImport } from './routes/api.rindle.mutate'
import { Route as ApiRindleQueryRouteImport } from './routes/api.rindle.query'
import { Route as ApiRindleReadRouteImport } from './routes/api.rindle.read'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const MineRoute = MineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleMutateRoute = ApiRindleMutateRouteImport.update({
  id: '/api/rindle/mutate',
  path: '/api/rindle/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleQueryRoute = ApiRindleQueryRouteImport.update({
  id: '/api/rindle/query',
  path: '/api/rindle/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRindleReadRoute = ApiRindleReadRouteImport.update({
  id: '/api/rindle/read',
  path: '/api/rindle/read',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/board': typeof BoardRoute
  '/mine': typeof MineRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/board': typeof BoardRoute
  '/mine': typeof MineRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/board': typeof BoardRoute
  '/mine': typeof MineRoute
  '/api/rindle/mutate': typeof ApiRindleMutateRoute
  '/api/rindle/query': typeof ApiRindleQueryRoute
  '/api/rindle/read': typeof ApiRindleReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/board'
    | '/mine'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/board'
    | '/mine'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/board'
    | '/mine'
    | '/api/rindle/mutate'
    | '/api/rindle/query'
    | '/api/rindle/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BoardRoute: typeof BoardRoute
  MineRoute: typeof MineRoute
  ApiRindleMutateRoute: typeof ApiRindleMutateRoute
  ApiRindleQueryRoute: typeof ApiRindleQueryRoute
  ApiRindleReadRoute: typeof ApiRindleReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mine': {
      id: '/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof MineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/mutate': {
      id: '/api/rindle/mutate'
      path: '/api/rindle/mutate'
      fullPath: '/api/rindle/mutate'
      preLoaderRoute: typeof ApiRindleMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/query': {
      id: '/api/rindle/query'
      path: '/api/rindle/query'
      fullPath: '/api/rindle/query'
      preLoaderRoute: typeof ApiRindleQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rindle/read': {
      id: '/api/rindle/read'
      path: '/api/rindle/read'
      fullPath: '/api/rindle/read'
      preLoaderRoute: typeof ApiRindleReadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BoardRoute: BoardRoute,
  MineRoute: MineRoute,
  ApiRindleMutateRoute: ApiRindleMutateRoute,
  ApiRindleQueryRoute: ApiRindleQueryRoute,
  ApiRindleReadRoute: ApiRindleReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
