//! Cross-engine differential test (spec `04` §9.4): replay a trace generated by
//! the REAL Zero `BTreeSet` (JS) through the Rust `BTree` and assert identical
//! results op-by-op — adds/deletes (return flag + size), has, get, forward and
//! reverse bounded seeks (inclusive and exclusive), full scans, and periodic
//! full-contents checkpoints. Structural invariants are checked after every op.
//!
//! The fixture `tests/fixtures/btree_js_trace.txt` is the frozen JS oracle;
//! regenerate with `npx tsx tools/gen_btree_trace.ts > tests/fixtures/...`.

use rindle::btree::{row_bound_of, BTree, RowStream};
use rindle::value::{owned_row as row, OwnedRow as Row, OwnedValue as Value, Sort};

fn s1() -> Sort {
    vec![(0, true)]
}

fn rk(k: i64) -> Row {
    row(vec![Value::Int(k)])
}

fn val(r: &Row) -> i64 {
    match &r.col(0).to_owned() {
        Value::Int(i) => *i,
        other => panic!("expected Int, got {other:?}"),
    }
}

fn parse_list(field: &str) -> Vec<i64> {
    if field == "-" {
        Vec::new()
    } else {
        field.split(',').map(|s| s.parse().unwrap()).collect()
    }
}

fn drain_forward(
    t: &BTree,
    bound: Option<&rindle::btree::RowBound>,
    inc: bool,
    sort: &Sort,
) -> Vec<i64> {
    let mut c = t.values_from(bound, inc, sort);
    std::iter::from_fn(|| c.next_row().map(val)).collect()
}

fn drain_reverse(
    t: &BTree,
    bound: Option<&rindle::btree::RowBound>,
    inc: bool,
    sort: &Sort,
) -> Vec<i64> {
    let mut c = t.values_from_reversed(bound, inc, sort);
    std::iter::from_fn(|| c.next_row().map(val)).collect()
}

#[test]
fn differential_vs_real_js_btreeset() {
    let sort = s1();
    let path = format!(
        "{}/tests/fixtures/btree_js_trace.txt",
        env!("CARGO_MANIFEST_DIR")
    );
    let trace = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read fixture {path}: {e} (regenerate with tools/gen_btree_trace.ts)")
    });

    let mut t = BTree::new();
    let mut ops = 0usize;

    for (lineno, line) in trace.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split(' ').collect();
        let ctx = || format!("line {} `{line}`", lineno + 1);
        match f[0] {
            "add" => {
                let k: i64 = f[1].parse().unwrap();
                let size: usize = f[2].parse().unwrap();
                let newly = f[3] == "1";
                let got = t.add(rk(k), &sort);
                assert_eq!(got, newly, "add newly-flag mismatch at {}", ctx());
                assert_eq!(t.len(), size, "add size mismatch at {}", ctx());
            }
            "del" => {
                let k: i64 = f[1].parse().unwrap();
                let removed = f[2] == "1";
                let size: usize = f[3].parse().unwrap();
                let got = t.delete(&rk(k), &sort);
                assert_eq!(got, removed, "del removed-flag mismatch at {}", ctx());
                assert_eq!(t.len(), size, "del size mismatch at {}", ctx());
            }
            "has" => {
                let k: i64 = f[1].parse().unwrap();
                let want = f[2] == "1";
                assert_eq!(t.has(&rk(k), &sort), want, "has mismatch at {}", ctx());
            }
            "get" => {
                let k: i64 = f[1].parse().unwrap();
                let got = t.get(&rk(k), &sort).map(val);
                let want = if f[2] == "-" {
                    None
                } else {
                    Some(f[2].parse().unwrap())
                };
                assert_eq!(got, want, "get mismatch at {}", ctx());
            }
            "scanfrom" => {
                let k: i64 = f[1].parse().unwrap();
                let inc = f[2] == "1";
                let want = parse_list(f[3]);
                let b = row_bound_of(&rk(k), &sort);
                assert_eq!(
                    drain_forward(&t, Some(&b), inc, &sort),
                    want,
                    "scanfrom at {}",
                    ctx()
                );
            }
            "revfrom" => {
                let k: i64 = f[1].parse().unwrap();
                let inc = f[2] == "1";
                let want = parse_list(f[3]);
                let b = row_bound_of(&rk(k), &sort);
                assert_eq!(
                    drain_reverse(&t, Some(&b), inc, &sort),
                    want,
                    "revfrom at {}",
                    ctx()
                );
            }
            "scanall" => {
                let want = parse_list(f[1]);
                assert_eq!(
                    drain_forward(&t, None, true, &sort),
                    want,
                    "scanall at {}",
                    ctx()
                );
            }
            "revall" => {
                let want = parse_list(f[1]);
                assert_eq!(
                    drain_reverse(&t, None, true, &sort),
                    want,
                    "revall at {}",
                    ctx()
                );
            }
            "checkpoint" => {
                let want = parse_list(f[1]);
                assert_eq!(
                    drain_forward(&t, None, true, &sort),
                    want,
                    "checkpoint at {}",
                    ctx()
                );
            }
            other => panic!("unknown op `{other}` at {}", ctx()),
        }
        // Structural invariants must hold after every JS-mirrored op.
        t.check_invariants(&sort)
            .unwrap_or_else(|e| panic!("invariant violated at {}: {e}", ctx()));
        ops += 1;
    }
    assert!(ops > 7000, "expected a substantial trace, got {ops} ops");
    eprintln!("differential vs real JS BTreeSet: {ops} ops replayed, all identical");
}
