// Generated by `rindle schema gen` from the daemon's introspected schema (GET /schema).
// Do not edit by hand — re-run the generator after each migration.
//
// Column kinds come from your declared SQL types: TEXT maps to string(), INTEGER/REAL to
// number(), and a column declared BOOLEAN/BOOL or JSON to boolean()/json(). The only thing the
// SQL can't carry is a refinement *within* a kind — the element type of json<T>(), or a
// string/number literal union — declare those ONCE in a hand-written module with
// refineTable(...) + refineSchema(...); they survive every regen of this file.

import { createSchema, number, string, table } from "@rindle/client";

export const category = table("category")
  .columns({
    id: string(),
    slug: string(),
    name: string(),
    description: string(),
    position: number(),
  })
  .primaryKey("id");

export const post = table("post")
  .columns({
    id: string(),
    threadId: string(),
    authorId: string(),
    body: string(),
    createdAt: number(),
    editedAt: number(),
    deleted: number(),
  })
  .primaryKey("id");

export const thread = table("thread")
  .columns({
    id: string(),
    categoryId: string(),
    authorId: string(),
    title: string(),
    createdAt: number(),
    lastPostAt: number(),
    locked: number(),
    pinned: number(),
  })
  .primaryKey("id");

export const user = table("user")
  .columns({
    id: string(),
    displayName: string(),
    avatarUrl: string(),
  })
  .primaryKey("id");

export const vote = table("vote")
  .columns({
    id: string(),
    postId: string(),
    userId: string(),
    createdAt: number(),
  })
  .primaryKey("id");

export const schema = createSchema({ tables: [category, post, thread, user, vote] });
